# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  microserviceapiwebapi:
    image: microserviceapiwebapi
    build:
      context: .
      dockerfile: import/WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5062:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4583:4566-4583"
